### PR TITLE
Table prefix

### PR DESCRIPTION
**Pull request by soyuka**
Hi,

Thought this could be usefull as it's in the laravel default database configuration! 

This is based on [Doctrine table prefix cookbook](http://doctrine-orm.readthedocs.org/en/latest/cookbook/sql-table-prefixes.html) with a small improvement on Sequences. It adds the prefix to the created sequence to match the table name.

I've tested this manually, but if you have any idea on how to test this without having to create mappings let me know and I'll add it!

### CODE REVIEW

**Comment by soyuka** [comment]
fixes #12

**Comment by kirkbushell** [comment]
@soyuka please write tests where it makes sense to do so. The table prefix listener could definitely do with a few.

**Comment by soyuka** [comment]
@kirkbushell I could add a test that's creating a table (sqlite) and check if the prefix has been added. Is that what you're asking?

Thanks!

**Comment by kirkbushell** [comment]
@soyuka just a unit test to make sure that the code you've written works. I'm sure it does - but it helps us to manage future change/pull requests if there's surrounding tests.

**Comment by soyuka** [comment]
That's the thing, I've add tests on Mappers but I don't know how I could test that the prefix is beeing added to the Table without creating a table :/. 

I'll try something with the metadata but if someone has a better idea, I'm listening!

**Comment by kirkbushell** [comment]
@soyuka you can mock out the calls in a unit test for now. End-to-end tests we don't really need at the moment as the package is rather small. We may need to look at doing something like that in the future, however.

**Comment by soyuka** [comment]
ok thanks, I'll look at this!

**Comment by soyuka** [comment]
Hope those fits!

Personal note: [this test class](https://github.com/doctrine/doctrine2/blob/master/tests/Doctrine/Tests/ORM/Mapping/ClassMetadataTest.php) was helpful.

**Pull request merged**
